Failing tests.

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,4 +1,7 @@
 #!/bin/bash
+
+ESC=$(printf "\033");
+
 FILES=$(
 	git diff-index HEAD \
 	| grep ".js$" \
@@ -8,29 +11,28 @@ FILES=$(
 
 echo $FILES
 
-errors=0
+ERRORS=0
 
 for file in $FILES; do
 
 	echo "Checking $file..."
-	error=$(npx babel $file 2>&1 1>/dev/null)
+	ERROR=$(npx babel $file 2>&1 1>/dev/null)
 
 	if [[ $? != 0 ]]; then
-		echo $error | sed "s,.*,    ${esc}[31m&${esc}[0m,";
-		errors=1
+		echo $ERROR | sed "s,.*,    ${ESC}[31m&${ESC}[0m,"
+		ERRORS=1
 	fi
 done
 
 make test
 
 if [[ $? != 0 ]]; then
-	echo $error | sed "s,.*,    ${esc}[31m&${esc}[0m,";
-	errors=1
+	ERRORS=1
 fi
 
-if [[ $errors == 1 ]]; then
-	echo "Commit aborted.";
-	exit 1;
+if [[ $ERRORS == 1 ]]; then
+	echo "Commit aborted."
+	exit 1
 else
-	exit 0;
+	exit 0
 fi
